export const javaHost = `https://accelerator-api-management.azure-api.net`;
export const LogoutUrl = `${javaHost}/user-service/api/v1/logout`;
export const sendOTPUrl = `${javaHost}/user-service/api/v1/users/forget-password/`;
export const validateOtpUrl = `${javaHost}/user-service/api/v1/users/validate-otp/`;
export const updatePasswordUrl = `${javaHost}/user-service/api/v1/users/change-password`;
export const addAllPeersUrl = `${javaHost}/graph-service/api/v1/graph/peers`;
export const addPeersBySearchUrl = `${javaHost}/graph-service/api/v1/graph/peers?keyword=`;
export const addPeersPaginationUrl = `${javaHost}/graph-service/api/v1/graph/peers?`;
export const toolbar = {
  options: [
    'inline',
    'blockType',
    'fontSize',
    'fontFamily',
    'emoji',
    'colorPicker',
    'list',
    'textAlign',

    'link',
    // 'embedded',

    // 'image',
    // 'remove',
    'history',
  ],
  inline: {
    inDropdown: false,
    className: undefined,
    component: undefined,
    dropdownClassName: undefined,
    options: [
      'bold',
      'italic',
      'underline',
      'strikethrough',
      'monospace',
      //   'superscript',
      //   'subscript',
    ],
    // list: { inDropdown: true },
    // textAlign: { inDropdown: true },
    // link: { inDropdown: true },
  },
  colorPicker: { className: 'demo-option-custom', popupClassName: 'popup-custom' },
  blockType: { className: 'demo-option-custom-wide', dropdownClassName: 'popup-custom' },
  fontSize: { className: 'demo-option-custom-medium', dropdownClassName: 'popup-custom' },
  fontFamily: { className: 'demo-option-custom-wide', dropdownClassName: 'popup-custom' },
  emoji: {
    // icon: BsAirplane,
    className: 'demo-option-custom',
    popupClassName: 'popup-custom',
  },
  history: {
    undo: {
      // icon: previous,
      className: 'demo-option-custom',
    },
    // redo: { icon: next, className: 'demo-option-custom' },
  },
};

export const apiData = {
  data: [
    {
      objectId: 'abc09@yopmail.com',
      interests: null,
      city: 'Noida',
      state: null,
      country: null,
      profession: null,
      speciality: 'ORTHO',
      age: 0,
      firstName: 'Shivam',
      lastName: 'Gupta',
      emailId: null,
      profilePictureUrl: null,
    },
    {
      objectId: 'nishanttiwari2@email.com',
      interests: null,
      city: null,
      state: null,
      country: null,
      profession: null,
      speciality: 'Ortho',
      age: 0,
      firstName: 'Nishant',
      lastName: 'Tiwari',
      emailId: null,
      profilePictureUrl: null,
    },
  ],
  success: null,
  errorCode: null,
  errorMessages: null,
  hasMorePage: false,
  pageNo: 0,
  pageSize: 20,
  totalElements: 2,
};
export const demoMyEventList = [
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
];
export const demoSuggestedEventList = [
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },

  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
];
export const demoBookmarkedEventList = [
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
  {
    img: 'https://images.pexels.com/photos/976866/pexels-photo-976866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    date: 'SAT 13 May',
    time: '11:00',
    name: 'Hip Hop Night',
    location: 'Cyber City, Gurugram',
    interested: 4,
  },
];
